### ISSUE TITLE
Donot depend on external API

### ISSUE THREAD

**Issue by harsha20599** [JemimaSadhika/edyst-s19-diy-pokedex#1]
It's great that you've found a solution but make sure that your API don't depend on external API like pokeapi in your case.

Try to build a scraper script which fetches all details at once and save that into a file.
Now modify your API to fetch details from that file.

Study others submissions in the slack to know more.

**Comment by JemimaSadhika** [comment]
Updated the code with a scrap.py which retrieves all necessary data from external API and stores in local file pokemondetails.json from which the required API app.py  fetches data.
